# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7170

###
GET https://localhost:7170/todos

###
GET https://localhost:7170/todos/1

###
POST https://localhost:7170/todos
content-type: application/json
{
  "Id": 2,
  "Name": "demo 2",
  "DueDate": "2024-07-12",
  "IsCompleted": false
}

###
DELETE https://localhost:7170/todos/2

###
GET https://localhost:7170/task/2
